<template>
	<div class="container">
		<div class="row min-vh-100 align-items-center justify-content-center">
			<div class="col-md-7">
				<div class="card border-0">
					<a
						href="https://nuxt.com"
						target="_blank"
						class="pb-4 d-flex gap-4 mx-auto justify-content-center"
					>
						<Icon name="logos:nuxt" size="2.5rem" width="auto" />
					</a>

					<h1 class="text-center h2 mb-3">
						Nuxt 3 + Bootstrap + jQuery Starter Template
					</h1>
					<p class="text-center mb-1">
						Let's make something great with this template.
					</p>
					<p class="text-center mb-3">
						If you don't belive that jQuery still can be installed on Nuxt 3,
						you can try it with browser console and type
						<code>$('div')</code> and hit <kbd>Enter</kbd> to see the result.
					</p>

					<div
						class="card card-body text-center mb-3 p-2 px-3 mx-auto"
						style="
							font-family: var(--bs-font-monospace);
							width: max-content;
							border-color: rgba(var(--bs-body-color-rgb), 0.05);
							background: rgba(var(--bs-body-color-rgb), 0.025);
						"
					>
						Get started by editing pages/index.vue and build something awesome.
						✨
					</div>

					<p class="mb-0 text-center">
						Created by <a href="https://instagram.com/cakadi.id">Cak Adi</a> and
						copyrighted on 2024.
					</p>
				</div>
			</div>
		</div>
	</div>
</template>

<script lang="ts">
export default defineComponent({
  name: 'Welcome'
});
</script>


<script lang="ts" setup>
useSeoMeta({
  title: 'Nuxt 3 Scaffolding',
  description: 'Nuxt 3 With Bootstrap and jQuery 4.0.0-beta',
  ogTitle: 'Nuxt 3 Scaffolding',
});

onMounted(() => {
  console.groupCollapsed("Open this magic");
  console.log("The console below is generated by $('div') with jquery@4.0.0-beta");
  console.log($('div'));
  console.groupEnd();
})
</script>

<style>
</style>