<script setup lang="ts">
const route = useRoute();

useSeoMeta({
  title: 'Nuxt 3 Scaffolding',
  description: 'Nuxt 3 With Bootstrap and jQuery 4.0.0-beta',
  ogTitle: 'Nuxt 3 Scaffolding',
});

onMounted(() => {
  console.groupCollapsed("Open this magic");
  console.log("The console below is generated by $('div') with jquery@4.0.0-beta");
  console.log($('div'));
  console.groupEnd();
})
</script>

<template>
	<div class="container">
		<div class="row min-vh-100 align-items-center justify-content-center">
			<div class="col-md-5">
				<div class="card p-4 rounded-4 card-body">
          <div class="mb-3 d-flex gap-4 justify-content-center">
            <span data-bs-toggle="tooltip" data-bs-title="Bootstrap v5.3.3"><Icon size="5rem" name="devicon:bootstrap" /></span>
            <span data-bs-toggle="tooltip" data-bs-title="Nuxt 3.11.2"><Icon size="5rem" name="logos:nuxt-icon" /></span>
            <span data-bs-toggle="tooltip" data-bs-title="jQuery 4.0.0-beta"><Icon size="5rem" name="devicon:jquery" /></span>
          </div>

					<h3 class="text-center">
						This Is Nuxt 3 With Bootstrap and jQuery 4.0.0-beta
					</h3>
					<p class="text-center">
						This Website is Scaffolding for Nuxt 3, Bootstrap 5.3.3 and jQuery
						4.0.0-beta. If you don't belive that jQuery still can be installed
            on Nuxt 3, you can try it with browser console and type 
            <code>$('div')</code> and hit <kbd>Enter</kbd> to see the result.
					</p>

          <p class="mb-0 text-center">Created by <a href="https://instagram.com/cakadi.id">Cak Adi</a> and copyrighted on 2024.</p>
				</div>
			</div>
		</div>
	</div>
</template>
